### PR TITLE
Refactor ai4e_azure_utils.py, sas_blob_utils.py, and path_utils.py

### PR DESCRIPTION
**Pull request by chrisyeh96**
Add unit tests for path_utils.py, and move all unit tests to tests/ directory

### CODE REVIEW

**Comment by calebrob6** [comment]
Hey @chrisyeh96, I think `tests/__init__.py` needs to exist in order to run `python -m unittest -v tests/test_path_utils.py`?

**Comment by yangsiyu007** [comment]
I've been running the test script directly e.g. `python synchronous_api_test.py`, but being able to run all tests in `/tests` would be useful. Let's add a "Testing" section in the main readme or a readme in `/tests` and write down the instructions for running these tests? The lack of an environment file might make this hard; we can assume people have all the packages. 

Otherwise looks good to me.

**Review by yangsiyu007 — APPROVED** [review]

**Comment by chrisyeh96** [comment]
@calebrob6 There is no need to have `tests/__init__.py` unless you are running Python 2.7. I'm able to run all the tests in the `tests/` folder directly through several means:

```bash
# with my terminal at ai4eutils/
python -m unittest tests/*.py
python -m unittest discover -s tests

# with my terminal at ai4eutils/tests/
python -m unittest *.py
python -m unittest discover
```

Note that the Python unittest library's "discover" feature by default assumes that test files are named `test*.py`, so I think it makes sense to follow that convention, instead of naming the test scripts `*_test.py`

**Comment by calebrob6** [comment]
@chrisyeh96 I'm not able to run the tests with Python 3.7 (see screenshot). Any ideas here?

image

**Comment by chrisyeh96** [comment]
@calebrob6  Hmm, I don't know why it doesn't work for you. Here's my output for reference:

```console
(cameratraps-classifier) cyeh@LAPTOP-QL6ULS0U:~/ai4eutils$ git pull
Already up to date.
(cameratraps-classifier) cyeh@LAPTOP-QL6ULS0U:~/ai4eutils$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(cameratraps-classifier) cyeh@LAPTOP-QL6ULS0U:~/ai4eutils$ python --version
Python 3.8.3
(cameratraps-classifier) cyeh@LAPTOP-QL6ULS0U:~/ai4eutils$ python -m unittest -v tests.test_path_utils
test_fileparts (tests.test_path_utils.Tests) ... ok
test_insert_before_extension (tests.test_path_utils.Tests) ... ok
test_split_path (tests.test_path_utils.Tests) ... ok
test_top_level_folder (tests.test_path_utils.Tests) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.004s

OK
(cameratraps-classifier) cyeh@LAPTOP-QL6ULS0U:~/ai4eutils$ echo $PYTHONPATH

(cameratraps-classifier) cyeh@LAPTOP-QL6ULS0U:~/ai4eutils$
```

**Comment by calebrob6** [comment]
If I switch to Python 3.8.3 it works fine!

**Pull request merged**
